info:
  contact: {}
paths:
  /healthz:
    get:
      description: 健康监测
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 健康监测接口
      tags:
      - healthz
  /random:
    get:
      description: 添加0-2秒随机延时
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 延时接口
      tags:
      - random
swagger: "2.0"
